src/Entity/Incidencia.php
<?php

namespace App\Entity;

use App\Repository\IncidenciaRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=IncidenciaRepository::class)
 */
class Incidencia
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=200)
     */
    private $titulo;

    /**
     * @ORM\Column(type="datetime")
     */
    private $fecha_creacion;

    /**
     * @ORM\Column(type="string", length=200)
     */
    private $estado;

    /**
     * @ORM\ManyToOne(targetEntity=Usuario::class, inversedBy="id_incidencia")
     */
    private $id_usuario;

    /**
     * @ORM\OneToMany(targetEntity=LineasDeIncidencia::class, mappedBy="incidencia")
     */
    private $id_LineasDeIncidencia;

    /**
     * @ORM\ManyToOne(targetEntity=Cliente::class, inversedBy="incidencias")
     */
    private $cliente;

    public function __construct()
    {
        $this->id_LineasDeIncidencia = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getTitulo(): ?string
    {
        return $this->titulo;
    }

    public function setTitulo(string $titulo): self
    {
        $this->titulo = $titulo;

        return $this;
    }

    public function getFechaCreacion(): ?\DateTimeInterface
    {
        return $this->fecha_creacion;
    }

    public function setFechaCreacion(\DateTimeInterface $fecha_creacion): self
    {
        $this->fecha_creacion = $fecha_creacion;

        return $this;
    }

    public function getEstado(): ?string
    {
        return $this->estado;
    }

    public function setEstado(string $estado): self
    {
        $this->estado = $estado;

        return $this;
    }

    public function getIdUsuario(): ?Usuario
    {
        return $this->id_usuario;
    }

    public function setIdUsuario(?Usuario $id_usuario): self
    {
        $this->id_usuario = $id_usuario;

        return $this;
    }

    /**
     * @return Collection|LineasDeIncidencia[]
     */
    public function getIdLineasDeIncidencia(): Collection
    {
        return $this->id_LineasDeIncidencia;
    }

    public function addIdLineasDeIncidencium(LineasDeIncidencia $idLineasDeIncidencium): self
    {
        if (!$this->id_LineasDeIncidencia->contains($idLineasDeIncidencium)) {
            $this->id_LineasDeIncidencia[] = $idLineasDeIncidencium;
            $idLineasDeIncidencium->setIncidencia($this);
        }

        return $this;
    }

    public function removeIdLineasDeIncidencium(LineasDeIncidencia $idLineasDeIncidencium): self
    {
        if ($this->id_LineasDeIncidencia->removeElement($idLineasDeIncidencium)) {
            // set the owning side to null (unless already changed)
            if ($idLineasDeIncidencium->getIncidencia() === $this) {
                $idLineasDeIncidencium->setIncidencia(null);
            }
        }

        return $this;
    }

    public function getCliente(): ?Cliente
    {
        return $this->cliente;
    }

    public function setCliente(?Cliente $cliente): self
    {
        $this->cliente = $cliente;

        return $this;
    }
}

src/Controller/IncidenciasController.php
<?php

namespace App\Controller;

use App\Entity\Incidencia;
use App\Entity\LineasDeIncidencia;
use App\Entity\Usuario;
use App\Entity\Cliente;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\Extension\Core\Type\ChoiceType;
use Symfony\Component\Form\Extension\Core\Type\SubmitType;
use Symfony\Bridge\Doctrine\Form\Type\EntityType;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\Routing\Annotation\Route;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\IsGranted;

class IncidenciasController extends AbstractController
{
    /**
     * @Route("/incidencias", name="incidencias")
     * 
     */
    public function index(): Response
    {
        $repositorio = $this->getDoctrine()->getRepository(Incidencia::class);
        $incidencias = $repositorio->findAll();
        return $this->render('incidencias/index.html.twig',
                        ['incidencias' => $incidencias]);
    }

    /**
     * @Route("/incidencias/insertar", name="insertar_incidencia")
     * 
     */
    public function insertar_incidencia(Request $request): Response
    {
        $incidencia = new Incidencia();
        $form = $this->createFormBuilder($incidencia)
                ->add('titulo', TextType::class,)
                ->add('cliente', EntityType::class, ['class' => Cliente::class, 'choice_label' => 'nombre'])
                ->add('estado', ChoiceType::class, [
                    'choices' =>
                    [
                        'Iniciada' => 'INICIADA',
                        'En Proceso' => 'EN_PROCESO',
                        'Resuelta' => 'RESUELTA',
                    ],
                ])
                ->add('insertar_incidencia', SubmitType::class, 
                        array(
                            'attr' => array('class' => 'btn btn-primary btn-block', 'label' => 'Insertar incidencia')
                        ))
                ->getForm();

        $form->handleRequest($request);
        if ($form->isSubmitted() && $form->isValid()) {
            $incidencia = $form->getData();
            //Guardamos el nuevo artículo en la base de datos
            $em = $this->getDoctrine()->getManager();
            $incidencia->setIdUsuario($this->getUser());
            $em->persist($incidencia);
            $em->flush();

            return $this->redirectToRoute('incidencias');
        }
        return $this->render('incidencias/insertar_incidencia2.html.twig', [
            'form' => $form->createView(),
        ]);
    }
    
    /**
     * @Route("/incidencias/insertar/cliente/{id}", name="insertar_incidencia_cliente")
     * 
     */
    public function insertar_incidencia_cliente(Request $request, Cliente $cliente): Response
    {
        $incidencia = new Incidencia();
        $form = $this->createFormBuilder($incidencia)
                ->add('titulo', TextType::class,)
                ->add('estado', ChoiceType::class, [
                    'choices' =>
                    [
                        'Iniciada' => 'INICIADA',
                        'En Proceso' => 'EN_PROCESO',
                        'Resuelta' => 'RESUELTA',
                    ],
                ])
                ->add('insertar_incidencia', SubmitType::class, 
                        array(
                            'attr' => array('class' => 'btn btn-primary btn-block', 'label' => 'Insertar incidencia')
                        ))
                ->getForm();

        $form->handleRequest($request);
        if ($form->isSubmitted() && $form->isValid()) {
            $incidencia = $form->getData();
            //Guardamos el nuevo artículo en la base de datos
            $em = $this->getDoctrine()->getManager();
            $incidencia->setIdUsuario($this->getUser());
            $incidencia->setCliente($cliente);
            $em->persist($incidencia);
            $em->flush();

            return $this->redirectToRoute('incidencias');
        }
        return $this->render('incidencias/insertar_incidencia.html.twig', [
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/ver_incidencias/{id}", name="ver_incidencia")
     * @param int $id
     * 
     */
    public function ver_incidencia(Incidencia $incidencia)
    {
        $repositorio = $this->getDoctrine()->getRepository(LineasDeIncidencia::class);
        $lineaIncidencias = $repositorio->findAll();
        return $this->render('incidencias/ver_incidencia.html.twig', ['incidencia' => $incidencia, 'lineaIncidencia' => $lineaIncidencias]);
    }

    /**
     * @Route("/borrar_incidencia/borrar/{id}", name="borrar_incidencia")
     * @return Response
     * 
     */
    public function borrar_incidencia(Incidencia $incidencia): Response 
    {
        $em = $this->getDoctrine()->getManager();
        $em->remove($incidencia);
        $em->flush();
        return $this->redirectToRoute('cliente');
    }

    /**
     * @Route("/insertar_comentario/{id}", name="insertar_comentario")
     * 
     */
    public function insertar_comentario(Request $request, Incidencia $incidencia): Response
    {
        $lineaIncidencia = new LineasDeIncidencia();
        $form = $this->createFormBuilder($lineaIncidencia)
                ->add('texto', TextType::class,)
                ->add('insertar_comentario', SubmitType::class, 
                        array(
                            'attr' => array('class' => 'btn btn-primary btn-block', 'label' => 'Insertar comentario')
                        ))
                ->getForm();

        $form->handleRequest($request);
        if ($form->isSubmitted() && $form->isValid()) {
            $lineaIncidencia = $form->getData();
            //Guardamos el nuevo artículo en la base de datos
            $em = $this->getDoctrine()->getManager();
            $lineaIncidencia->setIncidencia($incidencia);
            $em->persist($lineaIncidencia);
            $em->flush();

            return $this->redirectToRoute('incidencias');
        }
        return $this->render('incidencias/insertar_comentario.html.twig', ['form' => $form->createView(),]);
    }

    /**
     * @Route("/borrar_comentario/{id}", name="borrar_comentario")
     * @return Response
     * 
     */
    public function borrar_comentario(LineasDeIncidencia $lineaIncidencia): Response
    {
        $em = $this->getDoctrine()->getManager();
        $em->remove($lineaIncidencia);
        $em->flush();
        return $this->redirectToRoute('incidencias');
    }
}

templates/incidencias/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Incidencias{% endblock %}

{% block body %}
    {{ parent() }}
    <h1 style="color:black;margin-left: 400px;">Incidencias</h1>
    <br><br>
    {% for incidencia in incidencias %}
        <div class="incidencia" style="background-color: black; width: 20%; margin-left: 400px;">
            <h4><a href="{{  path('ver_incidencia',{id:incidencia.id}) }}">{{ incidencia.titulo }}</a><br>
                Borrar incidencia:
                <a href="{{ path('borrar_incidencia',{id:incidencia.id}) }}">X</a></h4>
        </div>
        <br>
    {% else %}
        No se ha encontrado ninguna incidencia
    {% endfor %}
    <div style="clear:both;"></div>
    {%  if app.user %}
        <a href="{{ path('insertar_incidencia') }}" class="btn btn-primary" role="button" style="margin-left: 400px;">Insertar Incidencia</a>
    {% endif %}
{% endblock %}

templates/incidencias/insertar_comentario.html.twig
{% extends 'base.html.twig' %}

{% block title %}Comentario{% endblock %}

{% block body %}
    {{ parent() }}
    <div class="card" style="color:black; height:auto;">
        <div class="card-header">
            <h2>Insertar Comentario</h2>
        </div>
        <div class="card-body">
            {{ form_start(form) }}
                {{ form_row(form.texto)}}
                {{ form_row(form.insertar_comentario, { 'label': 'Insertar Comentario' }) }}
            {{ form_end(form) }}
        </div>
    </div>
{% endblock %}

templates/incidencias/insertar_incidencia.html.twig
{% extends 'base.html.twig' %}

{% block title %}Incidencias{% endblock %}

{% block body %}
    {{ parent() }}
    <div class="card" style="height: auto; color: white;background-color: darkgray;">
        <div class="card-body">
            <h4 class="card-title">Insertar Incidencia</h4>
            {{ form_start(form) }}
                {{ form_row(form.titulo) }}
                {{ form_row(form.estado) }}
                {{ form_row(form.insertar_incidencia, { 'label': 'Insertar incidencia' }) }}
            {{ form_end(form) }}
        </div>
    </div>
{% endblock %}

templates/incidencias/insertar_incidencia2.html.twig
{% extends 'base.html.twig' %}

{% block title %}Incidencias{% endblock %}

{% block body %}
    {{ parent() }}
    <div class="card" style="height: auto; color: white;background-color: darkgray;">
        <div class="card-body">
            <h4 class="card-title">Insertar Incidencia</h4>
            {{ form_start(form) }}
                {{ form_row(form.titulo) }}
                {{ form_row(form.estado) }}
                {{ form_row(form.cliente) }}
                {{ form_row(form.insertar_incidencia, { 'label': 'Insertar incidencia' }) }}
            {{ form_end(form) }}
        </div>
    </div>
{% endblock %}

templates/incidencias/ver_incidencia.html.twig
{% extends 'base.html.twig' %}

{% block body %}
    <body style="color:black; height:auto;background-color: grey;">
    {{ parent() }}
    <div class="card" style="color:black; height:auto; background-color: grey;">
        <div class="card-body">
            <h4 class="card-title"style="background-color: darkgray;">Incidencia:</h4>
            <p class="card-text">{{incidencia.titulo}}</p>
            <h4 class="card-title"style="background-color: darkgray;">Estado:</h4>
            <p class="card-text">{{incidencia.estado}}</p>
            <h4 class="card-title"style="background-color: darkgray;">Fecha de la incidencia:</h4>
            <p class="card-text">{{ incidencia.fechaCreacion|date('d-m-Y h:i:s') }}</p>
            <a href="/cliente" class="btn btn-primary btn-block" role="button">Volver</a>
        </div>
    </div>
    
    </body>
{% endblock %}